### ISSUE TITLE
stupid bit defender STILL detects it.

### ISSUE THREAD

**Issue by Hardcore-fs** [MuntashirAkon/DPCIManager#4]
An infected file attempted to run on your device.
Threat name: Application.MAC.DirectHW.X
Path: /Users/comp_01/Downloads/DPCIManager.app/Contents/MacOS/DPCIManager
We quarantined the file to prevent malicious commands from being executed on your device.

**Comment by MuntashirAkon** [comment]
Interesting, previously they didn't detect anything. I'll try to remove any symbol related to `DirectHW`.

**Comment by MuntashirAkon** [comment]
Try this:
[DPCIManager.app.zip](https://github.com/MuntashirAkon/DPCIManager/files/2719949/DPCIManager.app.zip)

**Comment by Hardcore-fs** [comment]
the new one passes... 

I think maybe they are convinced the old one is mal ware because it writes to the hardware.

but they might update the virus defs once they see the same app with a different sig.
so it could be this one fails in the future.

**Comment by MuntashirAkon** [comment]
I think, previously, they didn't check for strings in Mach-O executables. But now they do. There was only one string in the app which referred to `DirectHW`. I simply removed it and it worked again.

Anyway, since there are no longer any references to `DirectHW`, I think the issue is finally solved.
