### ISSUE TITLE
Google Chrome and Version 1.9 and Earlier

### ISSUE THREAD

**Issue by nyhtml** [MuntashirAkon/DPCIManager#6]
**Google Chrome** is reporting the 1.9 app and earlier as bad even though the tools were said to be removed in version 1.8. So far, no issues downloading version 2.0 Keep up the great work.

**Google Chrome is up to date
Version 80.0.3987.162 (Official Build) (64-bit)**
![Google Chrome](https://user-images.githubusercontent.com/2177262/78151096-340b4100-7406-11ea-8b75-0936ec528aa4.png)

**Comment by MuntashirAkon** [comment]
DPCIManager v1.8 had a minor issue (see issue #4) which was fixed in v1.9. So, v1.9 and later do not have the tools that caused the antivirus software to detect it as a potential threat.

Having said that, Google Chrome was reporting that probably because this particular file wasn't in their database. It usually displays that warning when people attempt to download files from sites like Github where any file could easily be a malware. But it eventually whitelists the file once it is downloaded by a number of people (or some other factors that they didn't say). Also, it didn't show this warning before for that file, so my guess is that it is some how removed from their database (The [release page](https://api.github.com/repos/MuntashirAkon/DPCIManager/releases) is saying that v1.9 is downloaded at least 1021 times, so it's unlikely that nobody downloaded it from Google Chrome). Google support is saying that it may take upto 48 hours to add a new file to their database. So, this issue will probably be fixed after that time.

**Comment by nyhtml** [comment]
You have an option to bypass in Chrome or use Safari with no alerts. Just wanted you to know in case you wanted to note it or if someone (like Chris) planned to implement it in a package.
